development: 
  app_key: hupiz93f7yvrgo4
  app_secret: bp1dj2hl43dactw
  access_token: ack8hk8g97qf0f9
  access_token_secret: 57im50vdi6nga5a
  user_id: 134372155
  access_type: app_folder
  
production:
  app_key: hupiz93f7yvrgo4
  app_secret: bp1dj2hl43dactw
  access_token: <%= ENV['token'] %>
  access_token_secret: <%= ENV['secret'] %>
  user_id: 134372155
  access_type: app_folder



